[programs.localnet]
ags = "CarznLm8L4ZoAVX1yJj2FNbw5fHou69fPush7LFAML6j"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/ags.ts"
